### ISSUE TITLE
1:Many and Many:Many are not functional

### ISSUE THREAD

**Issue by ghost** [edurdias/RunningObjects#9]
1:Many and Many:Many relations are not functional.

Can you provide examples for 
1. Single Movie to many Directors, so you can see list of directors for the movie and navigate to Directors profile where you see what movies this Director directed.
2. Movies related many Categories, so you can see what movies are in category and under what categories is a particular movie, thus movies has many categories and category has many movies.

**Comment by edurdias** [comment]
Hi @georgih,

I have created an example demonstrating the use of relationships (1:many and many:many) with Running Objects and I figured out probably why you might faced this problem with *:many relationships. It was missing one file in the deployment, the bootstrap-typeahead.js file. 

It will be fixed in the next deployment early this week, but you can download it and add to your Scripts folder manually that it will work with no problems.

Regarding the examples, I've created a sample solution  that is available in the following URL and will be explained in a blog post late this week.

http://dl.dropbox.com/u/1625447/ro/files/RO-MovieDatabase-Relationships.zip

**Comment by ghost** [comment]
Excellent work! Cheers

**Comment by edurdias** [comment]
Hi @georgih, check out the blog post about associations and relationships:

http://weblogs.asp.net/eduardodias/archive/2012/09/05/running-objects-associations-and-relationships.aspx

Suggestions and comments are welcome.

-- Eduardo

**Comment by ghost** [comment]
Great job! Thanks
